name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ness_stretch
            asset_name: ness_stretch-linux-amd64
          - os: macos-latest
            artifact_name: ness_stretch
            asset_name: ness_stretch-macos-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          reposity: ${{ github.repository }}/rust
      - name: Build project
        run: cargo build --release
#       - name: copy file
#         uses: canastro/copy-file-action@master
#         with:
#           source: "target/release/ness_stretch"
#           target: "ness_stretch"
      - name: 'Tar files'
        run: tar -czvf ness_stretch.tar.gz -C target/release .
        
      - name: Upload binary to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: ness_stretch.tar.gz #target/release/${{ matrix.artifact_name }}
  windows:
    name: Windows
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: ness_stretch
            asset_name: ness_stretch-windows-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release --locked
      - name: Upload binary to release
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.asset_name }}
          path: D:\a\ness_stretch\${{ matrix.artifact_name }}
    
#         path: /home/runner/work/ness_stretch/ness_stretch/target/release/ness_stretch
#           repo_token: ${{ secrets.GITHUB_TOKEN }}
#           file: target/release/${{ matrix.artifact_name }}
#           asset_name: ${{ matrix.asset_name }}
#           tag: ${{ github.event.client_payload.new_version }}

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: cargo build --release
  
#     - uses: actions/upload-artifact@v2
#       with:
#         name: ness_stretch_linux
#         path: /home/runner/work/ness_stretch/ness_stretch/target/release/ness_stretch
        
  
